### ISSUE TITLE
missing path when installing

### ISSUE THREAD

**Issue by heyeddi** [rliou92/python-umonitor#3]
I installed this on Manjaro and the path to the config file was missing so the cli failed.

I had to mkdir -p ~/.config/umon/ 

  Operating System: Manjaro Linux
  Kernel: Linux 4.19.88-1-MANJARO
  Architecture: x86-64

**Comment by rliou92** [comment]
Thanks for letting me know!

**Comment by rliou92** [comment]
Fixed in f741e62d531c5c81ec0220526b9780dadebbc628
